#!/bin/bash
CONFIG=/boot/config.txt
# Grep for the strings we need to add to the config file,
# add after [pi4]
LINES=(
    "dtparam=i2c1=on,i2c_baudrate=400000"
    "gpio=17=op,dh"
    "gpio=26=op,dh"
    "gpio=25=op,dh"
    "dtoverlay=pwm,pin=13,func=4"
    "dtoverlay=pwm-fan"
    "dtoverlay=ssd1306-overlay,width=128,height=32,inverted,sequential"
    'dtoverlay=gpio-key,gpio=17,label="Top board",keycode=0x197'
)

IFS=""
ADD_LINES=""
for LINE in ${LINES[@]}; do
    sed -n '/^\[pi4\]/,/^\[.*/p' "${CONFIG}" | grep -q "${LINE}" \
        || ADD_LINES+="$LINE\n"
done
#IFS=$O_IFS

# Add the lines that are missing to the [pi4] section
sed -i "/^\[pi4\]/a ${ADD_LINES}" "${CONFIG}"
